[versions]
agp = "9.0.0"

applicationId = "org.example.project"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
android-versionCode = "1"
android-versionName = "1.0.0"

androidxActivity = "1.12.2"
androidxLifecycle = "2.9.6"
androidxSplashScreen = "1.2.0"

composeMultiplatform = "1.10.0"
composeMultiplatformMaterial3 = "1.9.0"

kotlin = "2.3.0"

[libraries]
# Gradle Plugins
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
composeMultiplatform-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeMultiplatform" }

# Compose Multiplatform
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-uiBackhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "composeMultiplatform" }
compose-uiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
compose-componentsResources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose-componentsUiToolingPreview = { module = "org.jetbrains.compose.components:components-ui-tooling-preview", version.ref = "composeMultiplatform" }

compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMultiplatformMaterial3" }

# Android
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-splash = { module = "androidx.core:core-splashscreen", version.ref = "androidxSplashScreen" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
compose-uiTest = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "composeMultiplatform" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinMultiplatformAndroid = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

# custom plugins
example-androidApplication = { id = "org.example.project.androidApplication", version = "unspecified" }
example-iosApplication = { id = "org.example.project.iosApplication", version = "unspecified" }
example-kmpLib = { id = "org.example.project.kmpLib", version = "unspecified" }
example-composeMultiplatform = { id = "org.example.project.composeMultiplatform", version = "unspecified" }
